### ISSUE TITLE
typo in Page 4 of the introduction

### ISSUE THREAD

**Issue by AvinoamK** [AvrahamRaviv/Deep-Learning-in-Hebrew#1]
On page 4 of the introduction, in the matrix summation, 
some of the indices in A+B are wrong. 
The top right should be 1,m (and not 1,n)
and the bottom left should be  n,1 and not m,1

Thanks :-)

**Comment by tony955084** [comment]
https://shopee.tw/product/4778468/2316179947?smtt=0.293761175-1614967009.9
