### ISSUE TITLE
chapter2- typo

### ISSUE THREAD

**Issue by NeteeraMC** [AvrahamRaviv/Deep-Learning-in-Hebrew#11]
![image](https://user-images.githubusercontent.com/66245078/161444474-38a4c766-36c4-4e58-bfa5-7c100b8ec8b1.png)
missing commas in phi(x)^T
should be:
(sqrt(2)x1s2, x1^2, x2^2)

**Comment by NeteeraMC** [comment]
in page 4

**Comment by AvrahamRaviv** [comment]
Thanks!
