### ISSUE TITLE
typo 

### ISSUE THREAD

**Issue by Yapibe** [AvrahamRaviv/Deep-Learning-in-Hebrew#16]
in the intro to ML, it says "הקלט נשאר לכאורה קבוע, אבל הפלט משתנה" and then follows to give an example: "עבור זמני יציאה שונים(!), האלגוריתם יעריך זמני נסיעה שונים" 
The problem is where i marked (!). if the example is constant input provides different output, it should be the same exit times produces different trip time.

**Comment by AvrahamRaviv** [comment]
זו לא טעות. בשונה ממערכת שאינה לומדת, עבורה הפלט קבוע ביחס לפלט, מערכת מבוססת ML יכולה לספק פלטים שונים עבור אותו קלט.
