### ISSUE TITLE
VAE 7.1.3

### ISSUE THREAD

**Issue by a-agmon** [AvrahamRaviv/Deep-Learning-in-Hebrew#5]
יכול להיות של הבנתי נכון, אבל בחלק 7.1.3 נאמר שאם נקח וקטור רנדומלי מהמרחב הלטנטי של אוטואנקודר רגיל אז סביר להניח שהוא לא יהיה דומה לדוגמא המקורית. אני לא לא בטוח שאני מבין למה. במידה ומדובר באוטואנקודר שמצליח לשחזר בצורה מדויקת את האינפוט שהוא מקבל אז הוא יהיה מסוגל לשחזר כל וקטור מהמרחב הלטנטי שלו כמו צריך, לא?

**Comment by AvrahamRaviv** [comment]
אפשר לבנות התפלגות מהוקטורים של המרחב הלטנטי וייתכן גם שהdecoder ידע לשחזר וקטורים אלו, אך אי אפשר לדעת איזו התפלגות תתקבל ועד כמה היא תהיה מורכבת. אם רוצים שההתפלגות של המרחב הלטנטי תהיה גאוסית, לא מספיק להשתמש בAE.  שימוש בVAE מאפשר לשלוט על הפרמטרים של ההתפלגות הלטנטית ככה שהיא תהיה קשורה להתפלגות המקורית.

**Comment by a-agmon** [comment]
Thanks for the answer

**Comment by AvrahamRaviv** [comment]
<p dir='rtl' align='right'> אפשר לבנות התפלגות מהוקטורים של המרחב הלטנטי וייתכן גם שהdecoder ידע לשחזר וקטורים אלו, אך אי אפשר לדעת איזו התפלגות תתקבל ועד כמה היא תהיה מורכבת. אם רוצים שההתפלגות של המרחב הלטנטי תהיה גאוסית, לא מספיק להשתמש בAE.  שימוש בVAE מאפשר לשלוט על הפרמטרים של ההתפלגות הלטנטית ככה שהיא תהיה קשורה להתפלגות המקורית.</p>
