### ISSUE TITLE
שגיאה בהגדרה

### ISSUE THREAD

**Issue by nadavpo** [AvrahamRaviv/Deep-Learning-in-Hebrew#6]
בעמוד 4, במקטע של כפל מטריצות.
כתוב שמספר השורות של המטריצה הראשונה צריך להיות שווה למספר העמודות של המטריצה השניה.
(אני נמנע משימוש באותיות אנגליות כי זה מסרבל את הכל)
אני מאמין שהכוונה הייתה ההיפך - עמודות בראשונה ושורות בשניה

**Comment by AvrahamRaviv** [comment]
Thanks!
