### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by nadavpo** [AvrahamRaviv/Deep-Learning-in-Hebrew#7]
last line on page 18, you forgot to split the summation

**Comment by AvrahamRaviv** [comment]
I think it's ok. Since the first 2 elements will be zeroing after the derivation, the rest is:
![gif](https://user-images.githubusercontent.com/56107590/137080613-fbd88d55-1dc0-49f0-802b-cffda20e722d.gif)

**Comment by AvrahamRaviv** [comment]
Checked
